services:
  zookeeper:
    image: confluentinc/cp-zookeeper:7.4.0
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  kafka:
    image: confluentinc/cp-kafka:7.4.0
    container_name: kafka
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:29092,PLAINTEXT_HOST://0.0.0.0:9092
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: 'true'

  postgres:
    image: postgres:15
    container_name: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: spotify_user
      POSTGRES_PASSWORD: spotify_pass
      POSTGRES_DB: spotify_db
    volumes:
      - postgres_data:/var/lib/postgresql/data

  spark-consumer:
    image: apache/spark:3.4.1
    container_name: spark-consumer
    user: root
    depends_on:
      - kafka
      - postgres
    environment:
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
      - POSTGRES_DB=spotify_db
      - POSTGRES_USER=spotify_user
      - POSTGRES_PASS=spotify_pass
      - KAFKA_BOOTSTRAP=kafka:29092
    volumes:
      - ./consumer:/app/consumer
      - ./postgresql-42.7.3.jar:/opt/spark/jars/postgresql-42.7.3.jar
      - spark_ivy_cache:/root/.ivy2
    command: >
      /opt/spark/bin/spark-submit
      --packages org.apache.spark:spark-sql-kafka-0-10_2.12:3.4.1
      --jars /opt/spark/jars/postgresql-42.7.3.jar
      /app/consumer/spark_consumer.py

volumes:
  postgres_data:
  spark_ivy_cache: